#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InterfazAdministrador.Data
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="db_asistencia")]
	public partial class DataClassesSPDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    #endregion
		
		public DataClassesSPDataContext() : 
				base(global::InterfazAdministrador.Properties.Settings.Default.db_asistenciaConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesSPDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesSPDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesSPDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesSPDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_Autenticar")]
		public ISingleResult<SP_AutenticarResult> SP_Autenticar([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Char(8)")] string idEmpleado)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idEmpleado);
			return ((ISingleResult<SP_AutenticarResult>)(result.ReturnValue));
		}
	}
	
	public partial class SP_AutenticarResult
	{
		
		private string _idEmpleado;
		
		private string _hash_contrasena;
		
		public SP_AutenticarResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idEmpleado", DbType="Char(8) NOT NULL", CanBeNull=false)]
		public string idEmpleado
		{
			get
			{
				return this._idEmpleado;
			}
			set
			{
				if ((this._idEmpleado != value))
				{
					this._idEmpleado = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hash_contrasena", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string hash_contrasena
		{
			get
			{
				return this._hash_contrasena;
			}
			set
			{
				if ((this._hash_contrasena != value))
				{
					this._hash_contrasena = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
